name: Simulate data

on:
  workflow_dispatch:
    inputs:
      sensors:
        description: "Número de sensores"
        required: false
        default: "4"
      interval_seconds:
        description: "Intervalo en segundos entre lecturas"
        required: false
        default: "5"
      duration:
        description: "Duración total (e.g. 1h, 30m, 45s)."
        required: false
        default: "5m"
      seed:
        description: "Semilla aleatoria (opcional)"
        required: false

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt

      - name: Run Simulator
        env:
          INFLUXDB_URL: ${{ secrets.INFLUX_URL }}
          INFLUXDB_TOKEN: ${{ secrets.INFLUXDB_TOKEN }}
          INFLUXDB_ORG: ${{ secrets.INFLUXDB_ORG }}
          INFLUXDB_BUCKET: ${{ secrets.INFLUX_BUCKET }}
        shell: bash
        run: |
          set -euo pipefail
          CMD=(python .github/scripts/simulate_data.py \
            --sensors "${{ github.event.inputs.sensors }}" \
            --interval "${{ github.event.inputs.interval_seconds }}")

          if [[ -n "${{ github.event.inputs.duration }}" ]]; then
            CMD+=(--duration "${{ github.event.inputs.duration }}")
          fi
          if [[ -n "${{ github.event.inputs.seed }}" ]]; then
            CMD+=(--seed "${{ github.event.inputs.seed }}")
          fi

          echo "Running: ${CMD[@]}"
          "${CMD[@]}"
