name: Simulate data

on:
  workflow_dispatch:
    inputs:
      start_date:
        description: "Fecha inicio (YYYY-MM-DD)"
        required: false
      end_date:
        description: "Fecha fin (YYYY-MM-DD)"
        required: false
      num_sensors:
        description: "Número de sensores"
        required: false
        default: "4"

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt

      - name: Run Simulator
        env:
          INFLUXDB_URL: ${{ secrets.INFLUX_URL }}
          INFLUXDB_TOKEN: ${{ secrets.INFLUXDB_TOKEN }}
          INFLUXDB_ORG: ${{ secrets.INFLUXDB_ORG }}
          START_DATE: ${{ github.event.inputs.start_date }}
          END_DATE: ${{ github.event.inputs.end_date }}
          NUM_SENSORS: ${{ github.event.inputs.num_sensors }}
        run: |
          python .github/scripts/simulate_data.py
